#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# abort_mismatch: dùng khi trạng thái portal thực tế khác giả định của ticket 04.
# Không suy đoán tiếp — dừng hẳn, để người dùng mang đúng thứ nhìn thấy quay lại chat.
abort_mismatch() {
  printf '\n'
  warn "Trạng thái portal khác với giả định. DỪNG Ở ĐÂY — đừng đổi gì thêm."
  say "Quay lại chat với Claude, mô tả CHÍNH XÁC những gì bạn thấy trên màn hình"
  say "(tên các platform, redirect URI liệt kê, giá trị toggle) để cập nhật lại kế hoạch"
  say "trước khi động vào app registration."
  exit 1
}

banner "Chuyển app Azure sang public client thật (ticket 04)"

say "App đăng ký trên Azure đang ở trạng thái lai: nhận luồng device code nhưng"
say "endpoint token vẫn đòi client_secret. Wizard này dẫn qua 3 việc trên portal:"
say "  1. Chuyển redirect URI từ nền tảng Web sang Mobile and desktop applications"
say "  2. Xác nhận Allow public client flows = Yes"
say "  3. Xoá client secret (KHÔNG LÙI ĐƯỢC)"
say ""
warn "Rủi ro đã biết: chuỗi refresh token 417 ký tự đang chạy được cấp cho danh tính"
warn "confidential, nhiều khả năng chết ngay khi app đổi loại. Bot sẽ ngưng ghi khoản"
warn "cho tới khi bạn gửi /reauth trong Telegram sau khi wizard này xong VÀ Claude đã"
warn "gỡ client_secret khỏi mã nguồn + Worker. Đừng chạy wizard này giữa lúc cần ghi gấp."

# ── Stage 1: xác nhận trạng thái hiện tại trước khi đổi gì ─────────────────
stage "Xác nhận trạng thái hiện tại (giả định — chưa ai nhìn portal)"
say "Ticket 04 suy luận trạng thái dưới đây từ việc luồng authorization code đòi"
say "secret, KHÔNG phải từ việc đã xem portal thật. Xác nhận trước khi đổi gì."
open_url "https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade"
step "Mở app đăng ký (tên trong docs/SETUP.md: telegram-expense-bot) → Authentication."
step "Nhìn mục 'Platform configurations'."
if ! confirm "Có đúng MỘT platform tên 'Web' với redirect URI dạng http://localhost:PORT/callback không?"; then
  abort_mismatch
fi
if confirm "Đã có sẵn platform 'Mobile and desktop applications' nào chưa (bất ngờ nếu có)?"; then
  abort_mismatch
fi
note "Khớp giả định: một platform Web, chưa có Mobile and desktop applications."

# ── Stage 2: chuyển redirect URI sang Mobile and desktop applications ──────
stage "Chuyển redirect URI sang Mobile and desktop applications"
say "Vẫn ở trang Authentication của app đó."
step "Ghi lại nguyên văn redirect URI đang nằm dưới Web (vd. http://localhost:8788/callback)."
step "Xoá platform 'Web' (biểu tượng thùng rác ở góc card, hoặc xoá từng redirect URI"
step "  rồi xoá platform khi nó rỗng)."
step "Bấm '+ Add a platform' → chọn 'Mobile and desktop applications'."
step "Dán ĐÚNG redirect URI vừa ghi lại vào ô 'Custom redirect URIs' → Configure."
if ! confirm "Redirect URI giờ nằm dưới Mobile and desktop applications, Web đã hết platform?"; then
  abort_mismatch
fi

# ── Stage 3: xác nhận Allow public client flows ─────────────────────────────
stage "Xác nhận Allow public client flows"
say "Vẫn ở trang Authentication, cuộn xuống mục 'Advanced settings'."
step "Nhìn toggle 'Allow public client flows'."
if ! confirm "Toggle đang bật (Yes) đúng như ticket 01 đã bật trước đây?"; then
  abort_mismatch
fi
note "Khớp giả định — không cần đổi gì ở bước này."

# ── Stage 4: lưu thay đổi ────────────────────────────────────────────────────
stage "Lưu thay đổi"
step "Bấm 'Save' ở cuối trang Authentication."
pause "Đã bấm Save và thấy thông báo lưu thành công?"

# ── Stage 5: [KHÔNG LÙI ĐƯỢC] xoá client secret ─────────────────────────────
stage "[KHÔNG LÙI ĐƯỢC] Xoá client secret"
warn "Bước này không lùi được. Sau khi xoá, chuỗi refresh token 417 ký tự đang chạy"
warn "(cấp cho danh tính confidential) nhiều khả năng chết ngay lập tức. Bot sẽ báo"
warn "hết hiệu lực xác thực cho tới khi bạn gửi /reauth trong Telegram."
say "Việc gỡ client_secret khỏi mã nguồn và Worker là việc của Claude, làm SAU khi"
say "bạn xong bước này — đừng tự sửa code hay chạy wrangler secret delete ở đây."
step "Vào 'Certificates & secrets' của app."
if confirm "Có đúng MỘT client secret liệt kê trong bảng (không phải nhiều/không phải zero)?"; then
  : # khớp giả định, đi tiếp
else
  abort_mismatch
fi
if confirm "XÁC NHẬN: xoá client secret này ngay bây giờ, chấp nhận bot ngưng ghi tạm thời?"; then
  step "Bấm biểu tượng thùng rác trên dòng secret đó → Yes để xác nhận xoá."
  pause "Đã xoá xong và bảng secret giờ trống?"
else
  warn "Đã dừng theo yêu cầu, chưa xoá gì. Chạy lại wizard khi sẵn sàng."
  exit 1
fi

# ── Stage 6: xong phần portal — quay lại Claude ─────────────────────────────
stage "Xong phần portal — quay lại Claude"
say "Portal đã chuyển xong. Còn lại là việc của Claude + của bạn cùng làm:"
step "1. Claude gỡ client_secret khỏi mã nguồn (src/, scripts/) và khỏi Worker,"
step "   sửa test hồi quy, chạy tsc + toàn bộ test."
step "2. Claude deploy Worker."
step "3. Bạn gửi /reauth trong Telegram, làm theo hướng dẫn đăng nhập lại."
step "4. Claude/bạn xác nhận: đổi chuỗi mới KHÔNG kèm secret → thành công;"
step "   thử gửi kèm secret → AADSTS90023."
step "5. Bạn thử ghi một khoản chi để xác nhận bot ghi được bình thường."
note "Azure AD có thể mất vài phút để lan truyền thay đổi Authentication — nếu"
note "/reauth báo lỗi lạ ngay sau khi vừa Save, đợi 2-3 phút rồi thử lại."
pause "Đọc xong, quay lại chat với Claude để làm tiếp?"

finish
